### ISSUE TITLE
Document how to mount folders for use with jellyfin

### ISSUE THREAD

**Issue by hawken93** [jellyfin/jellyfin-docs#10]
I think there have been some reliance on just giving emby a network path and having emby fix it. With jellyfin we have consensus that this is the task of the OS. So to be user friendly we need documentation on how to do this with some different OSes.

* docker
* debian stretch / buster
* arch
* windows (add network drive, right?)

(feel free to add more)
and for a few different network share types.

* nfs
* smb/cifs
* ceph

(feel free to add more)

I'm kind of old school, so I would do this in fstab. I'm unfamiliar with docker so any extra steps needed for docker needs to be documented.

**Comment by JustAMan** [comment]
Regarding Windows - most likely unc paths like `\\serv\share\folder` would work without mapping to a drive. This worked even back in win98 running DOS programs era :)

**Comment by oddstr13** [comment]
In regards of docker, this is a task handled by the host OS. Attempting to mount anything what so ever inside a docker container is no fun (requires running the docker container with full permissions).
