### ISSUE TITLE
Dead links (404)

### ISSUE THREAD

**Issue by berniegp** [jellyfin/jellyfin-docs#106]
At https://jellyfin.readthedocs.io/en/latest/#administrator-documentation

- Plugins: How to install plugins in Jellyfin.
- Port Bindings

Return a 404 page.

**Comment by Essasetic** [comment]
Oddly, the whole page now just redirects to the homepage for the documentation. I'll see if I can do anything about it but I doubt I can.

**Comment by Essasetic** [comment]
So... turns out the files don't exist. I'm sure they existed at one point which in that case I'll just merge them back into the source code. Odd this went unnoticed for quite a while though.

**Comment by Essasetic** [comment]
I've fixed it. You can close the issue now.
