### ISSUE TITLE
Undocumented rule for naming movies to be seen as one = "Movie Name (19XX) - .dvd.iso" 

### ISSUE THREAD

**Issue by Rudy-MS** [jellyfin/jellyfin-docs#11]
Couldn't get a movie with a dvd iso and a 480p MKV file to be seen as one in Emby or in Jellyfin. After talking to those cool cats in the Riot channel, we discovered that in order for the server to see multiple versions of a movie as one you must follow the rule of naming your movie as "movie name (19XX) - .dvd.iso". I was following this wiki instruction:

https://web.archive.org/web/20181216114832/https://github.com/MediaBrowser/Wiki/wiki/Movie-naming

to no avail. Luckily we found the solution. Seems like this should be updated in documentation or the code needs to be changed/updated. THank you! :)

**Comment by anthonylavado** [comment]
Specific section: https://web.archive.org/web/20181216114832/https://github.com/MediaBrowser/Wiki/wiki/Movie-naming#multi-version-movies

>Multiple versions of the same content can be stored in a single movie folder.
```
/Movies
  /300
    /300 - 1080p.mkv
    /300 - 720p.mp4
    /300 - extended edition.mp4
    /300 - directors cut.mp4
    /300 - 3D.hsbs.mp4
    /300 [720p].mp4
```
>Each version must begin with the folder name, followed by " - " or brackets " [720p] ". If this requirement is not met, they will be treated as separate videos. The text following the dash can be anything you want and will be what you see when Emby apps give you the option to select a specific version.

As the Emby Wiki is copyrighted, we must re-write this.
