### ISSUE TITLE
Add Live TV Guide Documentation

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-docs#125]
Add documentation similar to this: https://github.com/MediaBrowser/Wiki/wiki/Live-TV-Channel-Mapping

**Comment by dinki** [comment]
Just saw this after submitting this https://github.com/jellyfin/jellyfin-docs/pull/126

Mine is just a quick note but should help at least make it known that the user will need to set up channels and also provide information on the Docker HDHomerun pitfall of not running in host mode and having problems accessing the tuner.  This is a recurring problem for many users setting up for the first time.

I can circle back some other day to make this better but for now it should help as is.

**Comment by dinki** [comment]
See https://github.com/jellyfin/jellyfin-docs/pull/132
