### ISSUE TITLE
[Enhancement] Add some screenshots to the Readme

### ISSUE THREAD

**Issue by HavermansStef** [jellyfin/jellyfin-docs#13]

**Comment by anthonylavado** [comment]
The Readme is being kept really short on purpose - but we can look at adding screenshots to the docs :smile: 

Transferring to our Doc repo, and hopefully we'll have a nice website soon enough that can show off the app.

**Comment by joshuaboniface** [comment]
There's now screenshots on the main page (https://jellyfin.media) which I'd consider enough for now. We can expand it in the future.
