### ISSUE TITLE
Book media type documentation 

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-docs#135]
There is no page describing the book media type. File naming conventions and other relevant information should be added. 

See the [Music page](https://jellyfin.org/docs/general/server/media/music.html) for an example.

There is currently a broken link in `jellyfin-web` because this page does not exist. https://github.com/jellyfin/jellyfin-web/blob/master/src/controllers/medialibrarypage.js#L228

**Comment by Artiume** [comment]
This can be closed
