### ISSUE TITLE
Need to update `Nginx with subpath` section

### ISSUE THREAD

**Issue by JustAMan** [jellyfin/jellyfin-docs#150]
> @JustAMan I add `proxy_buffering off;`. So you may needs to update documents under `Nginx with subpath` section. :)

_Originally posted by @caoli5288 in https://github.com/jellyfin/jellyfin/issues/1663#issuecomment-544490803_

We need to add the `proxy_buffering off;` line to all nginx-related sections.

**Comment by caoli5288** [comment]
👍
