### ISSUE TITLE
Update Nginx configurations

### ISSUE THREAD

**Issue by dausruddin** [jellyfin/jellyfin-docs#158]
Nginx configuration for subpath needs to be updated due to base URL changing in the recent update.
I had to add `/jellyfin/` for the `proxy_pass` too.
I'm not sure about Nginx without subpath and the other configurations tho.

**Comment by theg00s3** [comment]
This should be closed, as the base url issue only affects those who upgraded from 10.4.0 to 10.4.1 . 
Source: https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1

**Comment by theg00s3** [comment]
This should be closed, as the base url issue only affects those who upgraded from 10.4.0 to 10.4.1 . 
Source: https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1

**Comment by JustAMan** [comment]
I think it still needs updating to add notes about proper baseurl usage.

**Comment by mcarlton00** [comment]
This can probably be closed now after https://github.com/jellyfin/jellyfin-docs/pull/230

**Comment by dausruddin** [comment]
Thanks.

Anyway, now I don't have to set baseurl anymore because I am using configs taken from 
https://www.reddit.com/r/jellyfin/comments/ekeszj/what_is_the_correct_config_for_nginx_with_subpath/

```
# Jellyfin
    # location /jellyfin {
    #     return 302 $scheme://$host/jellyfin/;
    # }
    
    location /jellyfin {
        # Proxy main Jellyfin traffic
        # The / at the end is significant.
        proxy_pass http://127.0.0.1:8096/;
    
        proxy_pass_request_headers on;
    
        proxy_set_header Host $host;
    
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
    
        # Disable buffering when the nginx proxy gets very resource heavy upon streaming
        proxy_buffering off;
    }
```

No need to set baseurl and it has been working fine for the past few weeks.
