### ISSUE TITLE
Describe how to enable/disable debug logging in the server

### ISSUE THREAD

**Issue by JustAMan** [jellyfin/jellyfin-docs#159]
As a stopgap measure we should be saying this much in documentation:

> In the `logging.json` file under the `configdir` (default `datadir/config`), you change:
> 
> ```
> "MinimumLevel": "Information",
> ```
> to
> 
> ```
> "MinimumLevel": "Debug",
> ```
> And then restart Jellyfin. The debug messages show up in the log with the tag `DBG`.

And hide the option from Web UI (or make it a link pointing to the documentation).

_Originally posted by @JustAMan in https://github.com/jellyfin/jellyfin/issues/1130#issuecomment-474395781_

**Comment by JustAMan** [comment]
Also describe log rotation, as written here: https://github.com/jellyfin/jellyfin/issues/2056#issuecomment-559254845

**Comment by cvium** [comment]
Restarting is no longer needed https://github.com/jellyfin/jellyfin/pull/1933
