### ISSUE TITLE
Not an issue, a fix

### ISSUE THREAD

**Issue by damnitall** [jellyfin/jellyfin-docs#180]
Apologies i have no idea where to share my experience with your (amazing) software but i am not at all familiar with git. Thought the documentation could probably benefit from my experience:

Setup:
- Asustor AS-5002t (Intel J1800 with QuickSync)
- running with Docker CE and Portainer
- original video with 17000kbps to transcode to 8mbps

What happens:
- activating HW transcode (Intel QuickSync) should free resources from the CPU and improve transcode speed
- unfortunately it is not the case. video freezes every other second

Fix:
- add a device on portainer pointing:
host: /dev/renderD128
container: /dev/dri/renderD128
- select VAAPI on the web interface instead of QuickSync

after this change the video is working beautifully. no buffering anymore.

**Comment by Artiume** [comment]
Created https://github.com/jellyfin/jellyfin-docs/pull/183 to fix.

**Comment by koolwiki** [comment]
@damnitall Could you please share me which OS do you use? I have a Intel J1800 PC too, but I can't use the hardware transcode on Synology.

**Comment by damnitall** [comment]
Only information I could find:

```
admin@AS-5002T:/volume1/home/admin $ uname -a
Linux AS-5002T 4.14.x #1 SMP Tue Nov 19 00:38:32 CST 2019 x86_64 GNU/Linux
```

Some (basic) troubleshooting:
Do you have /dev/dri/renderD128?
Do you run jellyfin as root?

**Comment by Artiume** [comment]
The native docker container can only run as root. If you try running it as a user tag, it fails. The lsio docker image should work fine and add the user to the video group

**Comment by Artiume** [comment]
I updated the hardware accel guide, check it out and see if it answers any questions and let me know what additional questions you may have that I can help add to the page

**Comment by koolwiki** [comment]
> I updated the hardware accel guide, check it out and see if it answers any questions and let me know what additional questions you may have that I can help add to the page

Could you please send me the link to the guide?

**Comment by koolwiki** [comment]
> Only information I could find:
> 
> ```
> admin@AS-5002T:/volume1/home/admin $ uname -a
> Linux AS-5002T 4.14.x #1 SMP Tue Nov 19 00:38:32 CST 2019 x86_64 GNU/Linux
> ```
> 
> Some (basic) troubleshooting:
> Do you have /dev/dri/renderD128?
> Do you run jellyfin as root?

Yes, I have /dev/dri/renderD128 and run jellyfin as root.

**Comment by damnitall** [comment]
> > I updated the hardware accel guide, check it out and see if it answers any questions and let me know what additional questions you may have that I can help add to the page
> 
> Could you please send me the link to the guide?

if I am not mistaken:
https://jellyfin.org/docs/general/administration/hardware-acceleration.html

**Comment by damnitall** [comment]
> > Only information I could find:
> > ```
> > admin@AS-5002T:/volume1/home/admin $ uname -a
> > Linux AS-5002T 4.14.x #1 SMP Tue Nov 19 00:38:32 CST 2019 x86_64 GNU/Linux
> > ```
> > 
> > 
> > Some (basic) troubleshooting:
> > Do you have /dev/dri/renderD128?
> > Do you run jellyfin as root?
> 
> Yes, I have /dev/dri/renderD128 and run jellyfin as root.

How do you run Jellyfin? As a docker container...?
Do you pass the device to the container?

**Comment by koolwiki** [comment]
> > > Only information I could find:
> > > ```
> > > admin@AS-5002T:/volume1/home/admin $ uname -a
> > > Linux AS-5002T 4.14.x #1 SMP Tue Nov 19 00:38:32 CST 2019 x86_64 GNU/Linux
> > > ```
> > > 
> > > 
> > > Some (basic) troubleshooting:
> > > Do you have /dev/dri/renderD128?
> > > Do you run jellyfin as root?
> > 
> > 
> > Yes, I have /dev/dri/renderD128 and run jellyfin as root.
> 
> How do you run Jellyfin? As a docker container...?
> Do you pass the device to the container?

I run Jellyfin as a docker container, and have passed the device to the container too. Some one says that Synology DMS only have diver for J3445. So, may be that is the reason.

**Comment by Artiume** [comment]
Run vainfo, you may have to install it first. What does it say

**Comment by JustAMan** [comment]
Closing as what the fix in original post says is present in the docs as of https://github.com/jellyfin/jellyfin-docs/pull/183
