### ISSUE TITLE
JF Docs Redirect

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-docs#187]
could https://jellyfin.readthedocs.io/ get a 302/301 to https://docs.jellyfin.org/ having a 30 second delay is a little long

**Comment by Artiume** [comment]
On the note of https://jellyfin.org/docs/ is there a way to add the TOC to the left panel like the rest of the documentation? I can't find it on git so I don't know if that page is hosted here

**Comment by anthonylavado** [comment]
We can’t control the page on RTD like we’d like to, but I can upload a shorter time, sure.

**Comment by anthonylavado** [comment]
Shortened to five seconds. Sound good?

**Comment by Artiume** [comment]
Yep. Don't forget to update the `You will be automatically redirected in 30 seconds.` :)
