### ISSUE TITLE
Add reverse proxy configuration

### ISSUE THREAD

**Issue by sauerj** [jellyfin/jellyfin-docs#2]
Running jellyfin behind a reverse proxy is a common practice. I think the docs should show working configurations for Apache2 and nginx.

I have a quite well working Apache2 VirtualHost configuration:

```
<VirtualHost *:80>
	ServerAdmin master@jellyfin.example.com
	ServerName jellyfin.example.com

	Redirect permanent / https://jellyfin.example.com

	ErrorLog /var/log/apache2/jellyfin.example.com-error.log
	CustomLog /var/log/apache2/jellyfin.example.com-access.log combined

</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>
	ServerAdmin master@jellyfin.example.com
	ServerName jellyfin.example.com

	ProxyPreserveHost On

	ProxyPass "/embywebsocket" "ws://127.0.0.1:8096/embywebsocket"
	ProxyPassReverse "/embywebsocket" "ws://127.0.0.1:8096/embywebsocket"

	ProxyPass "/" "http://127.0.0.1:8096/"
	ProxyPassReverse "/" "http://127.0.0.1:8096/"

	SSLEngine on
	SSLCertificateFile /etc/apache2/ssl/jellyfin.example.com.crt
	SSLCertificateKeyFile /etc/apache2/ssl/jellyfin.example.com.key

	ErrorLog /var/log/apache2/jellyfin.example.com-error.log
	CustomLog /var/log/apache2/jellyfin.example.com-access.log combined
</VirtualHost>
</IfModule>
```

It works with: Mozilla Firefox 60 / Linux, Mozilla Firefox 64 / Android, Google Chrome 71 / Android
It does **not** work with PS4 and the Emby Android Mobile or TV app. The UI can be displayed but no video.

Maybe we can use this example as a base and improve it to work with more clients.

**Comment by joshuaboniface** [comment]
Very good idea - I plan to document the 3 main reverse proxies (Apache, NGiNX, and HAProxy).

**Comment by sparky8251** [comment]
If we can figure out why those additional apps break for you that would be ideal.

At worst, we can say something like "these configs are known to work with the following apps. if you know how to fix another one, please open an issue on" and link here.

**Comment by hawken93** [comment]
Here was my end result..
https://github.com/jellyfin/jellyfin/issues/533#issuecomment-452909858

Using ProxyPass without rewrite rules did not work for me, I had to use rewrite rules to make it pass the get arguments...

And over https it suddenly wanted to connect to /socket, not /embywebsocket

So I wanted to ask if you could double check that you are in fact getting 101 on the websocket, not 404...

**Comment by sauerj** [comment]
@hawken93 I checked my vhost configuration and these are the http request and response headers.

I had some issues setting up the RewriteRule so as the ProxyPass and ProxyPassReverse directives are working for me, I gave up trying with Rewrite.
```
GET /embywebsocket?api_key=487116096bb84dbead82ed0807f96b3f&deviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo2MC4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzYwLjB8MTU0NjQyOTAwNDQwNw11 HTTP/1.1
Host: jellyfin.example.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://jellyfin.example.com
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: 3gsE0qZVVvp0btM4rvXdkA==
Cookie: ajs_user_id=null; ajs_group_id=null; ajs_anonymous_id=%2200000000000000000000000000%22
DNT: 1
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket

HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Accept: aYri2kLjFPZYY1VLtTY+DIbVj3I=
```

**Comment by hawken93** [comment]
The only difference is that I didn't have ProxyPassReverse on the websockets, so that must be it :)

**Comment by cfunseth** [comment]
Any interest in a Traefik configuration?  It can handle SSL certs directly and has some nice integrations with Docker using labels.

**Comment by JustAMan** [comment]
Can you build upon #40? The more options we have the better.

**Comment by joshuaboniface** [comment]
I'd say this is pretty much done, with all 3 major reverse proxies covered. If someone wants to add more PRs are always welcome!
