### ISSUE TITLE
DocFX CI builds fail

### ISSUE THREAD

**Issue by wwwutz** [jellyfin/jellyfin-docs#244]
The last time DocFX Build pipeline ran succesfully was run #20200216.4 . This ran with `DocFX release 2.48.1`.

With run #20200217.1 `DocFX release 2.49`. is used, which fails parsing several `triple-slash-comments`.

Any way to revert to 2.48.1 until this is fixed ?

**Comment by dkanada** [comment]
#246 :smile:

**Comment by wwwutz** [comment]
Great!  Thanks!
