### ISSUE TITLE
Update documenation wording to be less docker specific

### ISSUE THREAD

**Issue by rigtorp** [jellyfin/jellyfin-docs#318]
Docker is one of many container technologies. Podman is the preferred container solution on Fedora/Redhat/Centos for desktop/workstation and kubernetes is the preferred solution for servers. Synology etc will likely move to kubernetes as the supported container solution in the future. 

Let's add podman and kubernetes instructions. See #317 for podman instructions.

**Comment by Artiume** [comment]
I agree. Why not create a PR? It would help it get implemented faster :)

**Comment by rigtorp** [comment]
Yes I plan to. Submitted first PR with instructions for podman: #329
