### ISSUE TITLE
Add missing jellyfin-bin package to Arch Linux installation instructions

### ISSUE THREAD

**Issue by erkexzcx** [jellyfin/jellyfin-docs#341]
Hey. Not sure if reporting bug at the right place/repo, but [jellyfin-bin](https://aur.archlinux.org/packages/jellyfin-bin/) is missing from [here](https://jellyfin.org/docs/general/administration/installing.html#arch-linux).

I am the author & maintainer of [jellyfin-bin](https://aur.archlinux.org/packages/jellyfin-bin/) and if there is anything that needs to be done from my side - let me know.

**Comment by dkanada** [comment]
Looks like it's added now.
