### ISSUE TITLE
Update plugins page

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-docs#43]
Now that the plugin repo is live and (semi) populated, https://jellyfin.readthedocs.io/en/latest/administrator-docs/plugins/ should be updated on how to use them and (possibly) include a short description about what each plugin does.

I may get to this myself eventually, but I'm opening an issue so it doesn't get lost among other things

**Comment by anthonylavado** [comment]
New revised URL is: https://docs.jellyfin.org/general/server/plugins/index.html

In addition to listing what the plugin does, we should make sure we update the plugin descriptions as well.

**Comment by theg00s3** [comment]
I've done some of this in #176

**Comment by mcarlton00** [comment]
I'd say 176 covers just about anything I'd think to add.  Thanks
