### ISSUE TITLE
Improve client apps page

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-docs#46]
Add some more information to the client apps page

* Indicate current workable state (functional/non-functional/unknown)
* Links to install instructions

**Comment by theg00s3** [comment]
This seems to be complete, so you might want to consider closing this issue

**Comment by JustAMan** [comment]
It at least is missing WebOS mentioning there

**Comment by theg00s3** [comment]
Added the WebOS and React clients in #177
