### ISSUE TITLE
Docker compose v3 doesn't support group_add any more

### ISSUE THREAD

**Issue by darkdragon-001** [jellyfin/jellyfin-docs#475]
The [docs](https://github.com/jellyfin/jellyfin-docs/blob/master/general/administration/hardware-acceleration.md/#acceleration-on-docker) list an example `docker-compose.yaml` which uses version `3` together with `group_add` which was removed in this version (see https://github.com/docker/compose/issues/4700#issuecomment-416714975 and docker/cli#1318).

How can hardware acceleration be used with latest docker compose?

**Comment by Artiume** [comment]
use v2. i want to say 2.4 or 2.7 works

**Comment by ThibaultNocchi** [comment]
For me with compose 3.9 and docker-compose 1.28, `group_add` still works

**Comment by darkdragon-001** [comment]
@ThibaultNocchi It works _again_ [since 1.27](https://github.com/docker/cli/issues/1318#issuecomment-813750632). Thanks for confirming!

**Comment by ThibaultNocchi** [comment]
Np friend :)
