### ISSUE TITLE
Hypertext link address changed.

### ISSUE THREAD

**Issue by LegitGreenBoi** [jellyfin/jellyfin-docs#554]
https://jellyfin.org/docs/general/administration/hardware-acceleration.html

The hyperlink "Graphics Cards comparison using HWA" no longer leads to the comparison, but leads to Microsoft's IIS website.

**Comment by TimGels** [comment]
It works for me. Maybe it was down for a moment.

**Comment by ThibaultNocchi** [comment]
I confirm it works for me too :)
