### ISSUE TITLE
Chromecast - Nginx Content Security Policy 

### ISSUE THREAD

**Issue by sukram230799** [jellyfin/jellyfin-docs#588]
The URL for the Chromecast js-file seems to have changed. For this, the CSP in the Nginx-file seems to be wrong and Chromecasting doesn't work while jellyfin is served by nginx.

The old URL was `https://www.gstatic.com/cv/js/sender/v1/cast_sender.js` and the new URL seems to be `https://www.gstatic.com/eureka/clank/95/cast_sender.js`.

I'm not certain if that is the only valid URL under which the Chromecast file will be served, so I haven't created a pull request for it. But if the URL is changed in the `add_header Content-Security-Policy...` for nginx, Chromecasting becomes available again.

**Comment by sbranden** [comment]
@sukram230799, I can confirm the same issue and fix with nginx.  What log are you looking at or how did you determine the new URL?

**Comment by sukram230799** [comment]
@sbranden It was mentioned in the Chrome DevTools under the networking tab.

**Comment by ThibaultNocchi** [comment]
Well if it works again, I think it's pretty safe to open a PR :)

**Comment by ThibaultNocchi** [comment]
I _guess_ that should be safe, I'll look with others
