### ISSUE TITLE
Error Protocol In Nginx Default Http Conf

### ISSUE THREAD

**Issue by not94** [jellyfin/jellyfin-docs#626]
Hi, guys.It seems that http protocol should be in default nginx http configuration rather than https protocol.

`location = / {
        return 302 https://$host/web/;
    }`

https://github.com/jellyfin/jellyfin-docs/blob/103e687c04332a29ca0c2a0e2563a77ec8f4851d/general/networking/nginx.md?plain=1#L60

If this is a typo, maybe i could contribute to replace it with http protocol to fix this.

**Comment by ThibaultNocchi** [comment]
Seems like it is. Be my guest if you wanna open a PR for this :)
