### ISSUE TITLE
Addon vs Add-on inconsistency

### ISSUE THREAD

**Issue by whiteowl3** [jellyfin/jellyfin-docs#688]
We use both forms in the docs.  Only "Add-on" is suitable in English.  Is there any localization reason that we should be using both forms?  If not then we should move over to the technically correct "Add-on" in all instances.

**Comment by TimGels** [comment]
I was not aware that we use both. I fully agree that we should choose one form and stick with it to make it the least confusing as possible. "add-on" is fine for that in my eyes.
