### ISSUE TITLE
Add AAAA (IPv6) records for jellyfin.org

### ISSUE THREAD

**Issue by emlimap** [jellyfin/jellyfin-docs#695]
Github now supports IPv6 for Github Pages - https://github.blog/changelog/2021-09-30-enabling-ipv6-support-for-github-pages/

Could you please add AAAA (IPv6) DNS records to jellyfin.org, so the website is served over IPv6 for users on ISPs that offer IPv6.

```
2606:50c0:8000::153
2606:50c0:8001::153
2606:50c0:8002::153
2606:50c0:8003::153
```

From step 5 in https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by joshuaboniface** [comment]
These have been added, thanks! Glad to get the last part dual-stacked.

```
$ host jellyfin.org
jellyfin.org has address 185.199.110.153
jellyfin.org has address 185.199.108.153
jellyfin.org has address 185.199.109.153
jellyfin.org has address 185.199.111.153
jellyfin.org has IPv6 address 2606:50c0:8000::153
jellyfin.org has IPv6 address 2606:50c0:8002::153
jellyfin.org has IPv6 address 2606:50c0:8001::153
jellyfin.org has IPv6 address 2606:50c0:8003::153
```
