### ISSUE TITLE
Getting help is no help

### ISSUE THREAD

**Issue by jsmwrench** [jellyfin/jellyfin-docs#711]
Hello!

I purchased Jellyfin the other day and set it up just fine.  After rebooting my raspberry pi3b, I don't know how to connect to the vpn.  I looked in "Getting Help" on the web site, but I don't understand anything written in it.  It's like it was written for people that know how to code and probable don't need help.  Aren't there instructions for operating Jellyfin that a normal non-coding person can follow?

Thank you,
Ron
jsmwrench@gmail.com

**Comment by mcarlton00** [comment]
Friend, you're very, very confused.

Jellyfin is free on all platforms, and always will be.  You certainly didn't purchase anything from us.  There's not even a way _to_ purchase anything from us.  And there's no VPN involved in the app.

Further, if you're capable of having a github account and opening this issue, you're entirely capable of posting on [reddit](https://www.reddit.com/r/jellyfin/), or joining the chat rooms on [matrix](https://matrix.to/#/#jellyfinorg:matrix.org), [discord](https://discord.gg/zHBxVSXdBV), or IRC (if you're old school).  They all lead to the same place, and there's a large community of users willing and able to help with issues.
