### ISSUE TITLE
Add/change commands to reflect new build system (jellyfin/jellyfin#335)

### ISSUE THREAD

**Issue by EraYaN** [jellyfin/jellyfin-docs#8]
So apart from just telling people to use a script.

We should not be telling people to build from the Solution. People should build and publish from the *.csproj file.

So all the commands in the documentation need a final positional argument `Jellyfin.Server`.

This should be linked to jellyfin/jellyfin#335

**Comment by joshuaboniface** [comment]
Fixed in #31
