### ISSUE TITLE
Add clearer update instructions for Windows

### ISSUE THREAD

**Issue by mcarlton00** [jellyfin/jellyfin-docs#85]
Provide a set of instructions for Windows users on how to update their installations.

Referenced here:
https://www.reddit.com/r/jellyfin/comments/bysa53/jellyfin_1035_released/eqqz0hb/

**Comment by JustAMan** [comment]
Marking it as included in 10.4 as we're changing installation method which also leads to the need to manually uninstall previous version to avoid conflicts in running services.

**Comment by joshuaboniface** [comment]
I think we can get away with this in the downloads page on the website - we've gotta update that for the installer anyways.

**Comment by JustAMan** [comment]
@joshuaboniface I don't think it covers, as documentation still isn't updated.
I'm looking into https://jellyfin.org/docs/general/administration/installing.html#windows-x64x86:

![jf1](https://user-images.githubusercontent.com/1011526/66124599-7b4a7d80-e5ed-11e9-91f2-444e71136f22.png)
